# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: 'oneapi-src/oneTBB'
          submodules: 'recursive'
          path: 'oneTBB'
                    
      - uses: actions/checkout@v3
        with:
          repository: 'Blosc/c-blosc'
          submodules: 'recursive'
          path: 'c-blosc'
      
      - uses: actions/checkout@v3
        with:
          repository: 'AcademySoftwareFoundation/openvdb'
          submodules: 'recursive'
          path: 'openvdb'
          ref: 'v10.0.1'
      
      - uses: ilammy/msvc-dev-cmd@v1
      
      - uses: seanmiddleditch/gha-setup-ninja@master
      
      - run: |
              mkdir oneTBB/build
              mkdir c-blosc/build
              mkdir openvdb/build
              mkdir install
      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.1
        id: install-boost
        with:
            boost_version: 1.80.0
            platform_version: 2019
            toolset: msvc
            link: 'shared'
      
      - run: 'cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release -DTBB_TEST=OFF -DBOOST_ROOT=${{ steps.install-boost.outputs.BOOST_ROOT }}'
        working-directory: 'oneTBB/build'
      - run: 'cmake --build .'
        working-directory: 'oneTBB/build'
      - run: 'cmake --install . --prefix=${{github.workspace}}/install --config=Release'
        working-directory: 'oneTBB/build'
      
      - run: 'cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF -DBUILD_FUZZERS=OFF -DBUILD_BENCHMARKS=OFF -DTBB_ROOT=${{github.workspace}}/install'
        working-directory: 'c-blosc/build'
      - run: 'cmake --build .'
        working-directory: 'c-blosc/build'
      - run: 'cmake --install . --prefix=${{github.workspace}}/install --config=Release'
        working-directory: 'c-blosc/build'
        
      - run: 'cmake -G Ninja .. -DBoost_INCLUDE_DIR=${{ steps.install-boost.outputs.BOOST_ROOT }}/include -DBoost_LIBRARY_DIR_RELEASE=${{ steps.install-boost.outputs.BOOST_ROOT }}/lib -DZLIB_INCLUDE_DIR=${{github.workspace}}/install -DCMAKE_BUILD_TYPE=Release -DBlosc_ROOT=${{github.workspace}}/install -DOPENVDB_USE_FUTURE_ABI_10=ON -DOPENVDB_BUILD_BINARIES=OFF -DTBB_ROOT=${{github.workspace}}/install'
        working-directory: 'openvdb/build'
      - run: 'cmake --build .'
        working-directory: 'openvdb/build'
      - run: 'cmake --install . --prefix=${{github.workspace}}/install --config=Release'
        working-directory: 'openvdb/build'
      
      - uses: actions/upload-artifact@v3
        with:
          name: PrebuiltCMakeFiles
          path: install
