# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-13

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - run: 'uname -p'
      
      - uses: seanmiddleditch/gha-setup-ninja@master
      
      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.1
        id: install-aarch64-boost
        with:
            boost_version: 1.81.0
            platform: macos
            platform_version: 11
            boost_install_dir: ${{ github.workspace }}/boost-aarch64
            arch: aarch64
            link: shared
            toolset: clang
    
      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.1
        id: install-x86-boost
        with:
            boost_version: 1.81.0
            platform: macos
            platform_version: 11
            boost_install_dir: ${{ github.workspace }}/boost-x86
            arch: x86
            link: shared
            toolset: clang
      
      - run: mkdir boost-universal-libraries
      
      - run: mkdir -p boost-universal-libraries/arm64 && cp ${{ steps.install-aarch64-boost.BOOST_ROOT }}/lib/*.dylib boost-universal-libraries/arm64
      - run: cp ${{ steps.install-aarch64-boost.BOOST_ROOT }}/lib/*.a boost-universal-libraries/arm64
      
      - run: mkdir -p boost-universal-libraries/x86_64 && cp ${{ steps.install-x86-boost.BOOST_ROOT }}/lib/*.dylib boost-universal-libraries/x86_64
      - run: cp ${{ steps.install-x86-boost.BOOST_ROOT }}/lib/*.a boost-universal-libraries/x86_64
      
      - run: sh ${{ github.workspace }}/build_boost_universal.sh
        working-directory: boost-universal-libraries
      
      - uses: actions/upload-artifact@v3
        with:
          name: boost-1.81.0-macos-universal-binaries
          path: boost-universal-libraries/universal
      
