# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-13

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - run: 'uname -p'
      
      - uses: seanmiddleditch/gha-setup-ninja@master
      
      - uses: actions/checkout@v3
        with:
          repository: 'boostorg/boost'
          submodules: 'recursive'
          ref: 'boost-1.82.0'
          path: 'boost'
      
      - run: 'sh ${{ github.workspace }}/build_boost_universal.sh'
        working-directory: boost/
      
      - uses: actions/upload-artifact@v3
        with:
          name: boost-1.82.0-macos-x86_64-binaries
          path: boost/
      
